name: Build and Release

on:
  push:
    tags:
      - '*'
    branches:
      - main
      - feat/pyinstaller

env:
  MICROPYTHON_PICO_UF2_URL: https://micropython.org/resources/firmware/RPI_PICO-20241129-v1.24.1.uf2

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Download micropython binary
        run: |
          IWR -OutFile micropython_pico.uf2 -Uri ${{ env.MICROPYTHON_PICO_UF2_URL }}

      - name: Install PyInstaller
        run: |
          pip install pyinstaller pyserial tqdm

      - name: Build executable
        run: |
          pyinstaller micropython_rfunit.spec

      - name: Rename README
        run: |
          cp README_easy.txt README.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            LICENSE
            CREDITS
            README.txt
            pi_pico_diagram_phat.png
            pi_pico_diagram_one_s.png
            micropython_pico.uf2

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Create release zip
        run: |
          mkdir release
          cp LICENSE release/
          cp CREDITS release/
          cp dist/* release/
          cp README.txt release/
          cp pi_pico_diagram_phat.png release/
          cp pi_pico_diagram_one_s.png release/
          cp micropython_pico.uf2 release/
          cd release
          7z a ../rfunit-win64-${{ github.ref_name }}.zip *
          cd ..

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_notes: false
          files: |
            rfunit-*.zip
