name: Build and Release

on:
  push:
    tags:
      - '*'
    branches:
      - main
      - feat/pyinstaller

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install PyInstaller
        run: |
          pip install pyinstaller pyserial

      - name: Build executable
        run: |
          pyinstaller micropython_rfunit.spec

      - name: Rename README
        run: |
          cp README_easy.txt README.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            README.txt
            pi_pico_diagram.jpg

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Create release zip
        run: |
          mkdir release
          cp dist/* release/
          cp README.txt release/
          cp pi_pico_diagram.jpg release/
          cd release
          7z a ../rfunit-win64-${{ github.ref_name }}.zip *
          cd ..

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          generate_notes: false
          files: |
            rfunit-*.zip
